# Water enviromental package profiling
This notebooks profiles biosamples indicated as being part of a water-related package.  
Profiling, in this sense, means that descrptive analsyis done on the field types, field values, and amount of missing values.
Steps:
1. Load and subset/slice data
2. Normalize water env_package labels
3. Describe water env_packages. This includes:
  - all water-related packages
  - env_packages labled as 'water'
  - env_packages labled as 'waste water'
  - env_packages labled as 'sea water'
  - env_packages labled as 'Deep-sea water'
  - env_packages labled as 'fresh water'
  - env_packages labled as 'sterile water'
  - env_packages labled as 'Coastal water body (ENVO:02000049)'

In [1]:
import pandas as pds
import numpy as np
import csv

# 1. Load and subset/slice data

### Load non-human dataset created by notebook `build-non-human-samples.ipynb`

In [2]:
df = pds.read_csv('../../target/non-human-samples.tsv.gz', sep='\t', dtype=str, quoting=csv.QUOTE_NONE)
len(df)

45951

### get list of env packages the have the string 'water' in them

In [3]:
waterPackages = [x for x in df.env_package.unique() if 'water' in x.lower()]

In [4]:
waterPackages

['water',
 'MIMARKS_water',
 'MIGS/MIMS/MIMARKS.wastewater',
 'MIGS/MIMS/MIMARKS.water',
 'seawater',
 'wastewater/sludge',
 'wastewater|sludge',
 'wastewater',
 'fresh water',
 'freshwater sediment',
 'sea water',
 'sterile water',
 'Coastal water body (ENVO:02000049)',
 'sea water, [ENVO:00002149]',
 'Water',
 'wastewater sludge',
 'Sea water',
 'Deep-sea water']

### filter out packages containing the strings 'sludge' and 'sediment'

In [5]:
waterPackages = [x for x in waterPackages if 'sludge' not in x.lower()]
waterPackages = [x for x in waterPackages if 'sediment' not in x.lower()]

In [6]:
waterPackages

['water',
 'MIMARKS_water',
 'MIGS/MIMS/MIMARKS.wastewater',
 'MIGS/MIMS/MIMARKS.water',
 'seawater',
 'wastewater',
 'fresh water',
 'sea water',
 'sterile water',
 'Coastal water body (ENVO:02000049)',
 'sea water, [ENVO:00002149]',
 'Water',
 'Sea water',
 'Deep-sea water']

### create slice of data based on water package list

In [7]:
sliceDf = df[df.env_package.isin(waterPackages)]
len(sliceDf)

18615

# 2. Normalize water env_package labels
Some of the evn_packages seem to refer to the same water package, but with syntax variations (e.g. 'Water', 'MIMARKS_water').  
To account for this, create column 'norm_env_package' to hold normalized values and normalize data as follows:
1. Map 'Sea water', 'seawater', 'sea water', 'sea water, [envo:00002149]' to 'sea water'.
2. Map 'wastewater', 'MIGS/MIMS/MIMARKS.wastewater' to 'waste water'
3. Map 'water', 'Water', 'mimarks_water', 'migs/mims/mimarks.water' to 'water'
4. Leave 'Deep-sea water', 'fresh water', 'sterile water', and ''Coastal water body (ENVO:02000049)' as the same values

In [8]:
def mapWaterPackage(val):
    if val in ['Sea water', 'seawater', 'sea water', 'sea water, [ENVO:00002149]']:
        return 'sea water'
    elif val in ['wastewater', 'MIGS/MIMS/MIMARKS.wastewater']:
        return 'waste water'
    elif val in ['water', 'Water', 'MIMARKS_water', 'MIGS/MIMS/MIMARKS.water']:
        return 'water'
    else:
        return val

In [9]:
sliceDf['norm_env_package'] = sliceDf['env_package'].map(lambda x: mapWaterPackage(x))

/Users/wdduncan/repos/INCATools/biosample-analysis/src/.env/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.


### verify all values have been normalized (i.e., counts match) and get counts of packages

In [10]:
sliceDf.norm_env_package.count() == len(sliceDf)

True

In [11]:
sliceDf.groupby('norm_env_package')['norm_env_package'].count().sort_values(ascending=False)

norm_env_package
water                                 18139
waste water                             399
sterile water                            35
fresh water                              27
sea water                                13
Deep-sea water                            1
Coastal water body (ENVO:02000049)        1
Name: norm_env_package, dtype: int64

# 3. Describe all water env_packages

### define some helper functions

In [12]:
def replaceMissingValues(df):
    # many of the missing values have values beginning with 'Missing'; e.g.: Missing: Not provided
    # replace these with NaN
    for idx in df.index:                 # iterate over indexes
        row = df.loc[idx,:]              # get the dataframe row; note: this is of type Pandas Series
        for field in row.index:          # iterate over each field (i.e., series index) and replace 'Missing' with Nan
            val = row[field]
            if not pds.isnull(val) and val.lower()[:7] == 'missing': row[field] = np.nan
    return df

In [13]:
def getReducedDatame(df):
    # many of the missing values have values beginning with 'Missing'; e.g.: Missing: Not provided
    # replace these with NaN so that the decribe function can count properly
    reducedDf = replaceMissingValues(df)
    
    # remove columns from the reduced dataframe that don't have data
    describeDf = df.describe()                   # describe the dataframe
    valueCount = describeDf.loc['count']         # get count row / index
    zeroCount = valueCount[valueCount == 0]      # subset valueCount to those with counts of 0
    zeroCountCols = zeroCount.index              # find the columns with zero counts
    reducedDf = df.drop(zeroCountCols, axis=1)   # drop columns that have counts of 0 (i.e., no data)
    
    return reducedDf

In [14]:
def getDescibeDf(df):
    describeDf = df.describe().transpose()                                                  # describe df; note: the transpose
    describeDf['pct_non_null'] =\
        describeDf['count'].map(lambda x: 0.00 if x == 0 else round((x / len(df)) * 100, 2)) # add column to show the percent of non-null data
    return describeDf

## Desribe all water samples

### get reduced dataframe (i.e., columns with no data removed) and describe

In [15]:
reducedDf = getReducedDatame(sliceDf) 
reducedDescribe = getDescibeDf(reducedDf)

/Users/wdduncan/repos/INCATools/biosample-analysis/src/.env/lib/python3.7/site-packages/ipykernel_launcher.py:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


### save copy of water-related packages

In [48]:
reducedDf.to_csv('../../target/water-related-samples.tsv.gz', sep='\t', compression='gzip', index=False)

In [49]:
reducedDf.shape

(18615, 97)

In [17]:
pds.set_option('max_rows', None)
reducedDescribe.sort_values(by='pct_non_null', ascending=False)

count unique  \
norm_env_package     18615      7   
package              18615     19   
taxonomy_name        18615    105   
taxonomy_id          18615    107   
id                   18615  18615   
env_package          18615     14   
env_local_scale      18525    539   
env_broad_scale      18517    314   
env_medium           17753    232   
depth                15747    868   
geo_loc_name         14219    526   
temp                 11495   2946   
project_name          9611    339   
elev                  8246    212   
collection_date       6753   1303   
investigation_type    5877     14   
salinity              5373    887   
ph                    5288    441   
oxygen                4033    425   
phosphate             3948    407   
nitrate               3920    875   
diss_org_carb         3130    885   
diss_inorg_carb       3048    961   
lat_lon               3032    826   
ph_meth               3010      3   
chloride              2875    145   
tot_diss_nitro        2854     99   
potassium             2815    251   
calcium               2805   1660   
sulfate               2795    164   
magnesium             2787    987   
sodium                2779    441   
diss_oxygen           2763    721   
diss_carb_dioxide     2754    228   
conduc                1476    452   
silicate               846    529   
chlorophyll            820    230   
samp_collect_device    803     43   
samp_size              702     39   
density                684    200   
ammonium               684    246   
nitrite                631    142   
host_taxid             572     12   
samp_mat_process       533     21   
tot_depth_water_col    505    101   
samp_store_temp        499      8   
samp_store_loc         466      5   
wind_speed             366     59   
oxy_stat_samp          341      2   
phaeopigments          281     19   
atmospheric_data       255     31   
fluor                  215    107   
rel_to_oxygen          179     12   
samp_store_dur         158     14   
ref_biomaterial        139     19   
part_org_carb          134     94   
part_org_nitro         134     89   
organism_count         120     10   
isol_growth_condt      118     26   
pressure               108     13   
turbidity              102     48   
alkalinity              99     49   
experimental_factor     97     14   
nitro                   93     63   
primary_prod            80     65   
misc_param              78      3   
org_nitro               72     38   
tot_nitro               72     23   
org_carb                72     42   
salinity_meth           68      2   
tot_phosp               65     22   
light_intensity         65     27   
bacteria_carb_prod      60      6   
samp_salinity           59      5   
perturbation            53     26   
redox_potential         50     44   
diss_org_nitro          49      9   
host_height             37      2   
host_age                36      2   
num_replicons           34      6   
tot_carb                30     27   
heavy_metals_meth       27      1   
samp_vol_we_dna_ext     24      2   
tot_part_carb           22     22   
ploidy                  16      3   
carb_nitro_ratio        14     14   
biotic_relationship     13      1   
trophic_level           13      4   
host_life_stage         12      2   
extreme_salinity        12      6   
suspend_part_matter     10     10   
propagation              8      4   
estimated_size           8      4   
slope_aspect             3      1   
biomass                  2      2   
n_alkanes                1      1   
tidal_stage              2      1   

                                                                   top   freq  \
norm_env_package                                                 water  18139   
package                                                    Generic.1.0  15933   
taxonomy_name                                        marine metagenome   6530   
taxonomy_id                                                     408172

## Describe env_packages labled as 'water'

In [18]:
waterDf = getReducedDatame(reducedDf[reducedDf.norm_env_package == 'water'].copy()) # note: a copy of the dataframe is being used
waterDescribe = getDescibeDf(waterDf)

In [19]:
waterDf.shape

(18139, 96)

In [20]:
waterDescribe.sort_values(by='pct_non_null', ascending=False)

count unique  \
norm_env_package     18139      1   
env_package          18139      4   
package              18139     13   
taxonomy_name        18139     85   
taxonomy_id          18139     87   
id                   18139  18139   
env_broad_scale      18050    257   
env_local_scale      18039    440   
env_medium           17304    198   
depth                15564    858   
geo_loc_name         13702    459   
temp                 10547   2929   
project_name          9259    283   
elev                  8171    208   
collection_date       6295   1138   
investigation_type    5477     14   
ph                    4010    428   
diss_oxygen           2585    719   
salinity              2581    883   
lat_lon               2563    711   
diss_org_carb         2493    884   
nitrate               2260    872   
tot_diss_nitro        2180     98   
phosphate             2094    382   
potassium             2009    250   
calcium               1999   1659   
magnesium             1981    986   
sodium                1971    439   
diss_inorg_carb       1722    960   
oxygen                1511    424   
conduc                1468    444   
diss_carb_dioxide     1335    227   
silicate               846    529   
chlorophyll            820    230   
samp_collect_device    798     40   
samp_size              697     38   
density                682    199   
nitrite                631    142   
ammonium               615    245   
samp_mat_process       517     18   
host_taxid             508      9   
tot_depth_water_col    505    101   
chloride               482    144   
samp_store_temp        459      5   
samp_store_loc         440      3   
sulfate                402    163   
wind_speed             366     59   
oxy_stat_samp          328      1   
phaeopigments          281     19   
atmospheric_data       255     31   
fluor                  209    106   
ph_meth                200      1   
rel_to_oxygen          160     10   
samp_store_dur         146      8   
part_org_carb          134     94   
part_org_nitro         134     89   
organism_count         120     10   
pressure               108     13   
alkalinity              99     49   
experimental_factor     97     14   
nitro                   93     63   
turbidity               84     30   
isol_growth_condt       81     10   
misc_param              78      3   
light_intensity         65     27   
primary_prod            66     64   
tot_nitro               62     22   
bacteria_carb_prod      60      6   
ref_biomaterial         59     10   
tot_phosp               55     21   
perturbation            53     26   
redox_potential         50     44   
samp_salinity           49      1   
diss_org_nitro          49      9   
org_carb                48     41   
org_nitro               48     37   
host_height             37      2   
host_age                36      2   
tot_carb                30     27   
num_replicons           27      3   
heavy_metals_meth       27      1   
tot_part_carb           22     22   
samp_vol_we_dna_ext     14      1   
carb_nitro_ratio        14     14   
salinity_meth           12      1   
host_life_stage         12      2   
extreme_salinity        12      6   
suspend_part_matter     10     10   
ploidy                   6      1   
propagation              6      2   
estimated_size           6      2   
slope_aspect             3      1   
biomass                  2      2   
n_alkanes                1      1   
biotic_relationship      1      1   
tidal_stage              2      1   

                                                                   top   freq  \
norm_env_package                                                 water  18139   
env_package                                                      water  16367   
package                                                    Generic.1.0  15856   
taxonomy_name                                        marine metagenome   6530   
taxonomy_id               

## Describe env_packages labled as 'waste water'

In [21]:
wasteWaterDf = getReducedDatame(reducedDf[reducedDf.norm_env_package == 'waste water'].copy()) # note: a copy of the dataframe is being used
wasteWaterDescribe = getDescibeDf(wasteWaterDf)

In [22]:
wasteWaterDf.shape

(399, 38)

In [23]:
wasteWaterDescribe.sort_values(by='pct_non_null', ascending=False)

count unique  \
norm_env_package      399      1   
taxonomy_id           399     20   
env_medium            399     35   
env_broad_scale       399     56   
id                    399    399   
env_local_scale       399     96   
taxonomy_name         399     20   
env_package           399      2   
package               399      7   
collection_date       396    185   
geo_loc_name          395     68   
investigation_type    389      5   
lat_lon               364    111   
project_name          331     52   
ref_biomaterial        78      7   
ph                     52     36   
samp_store_temp        40      5   
depth                  36      6   
temp                   34     26   
samp_store_loc         26      2   
isol_growth_condt      24      7   
phosphate              22     22   
turbidity              18     18   
rel_to_oxygen          16      3   
samp_mat_process       15      2   
oxy_stat_samp          13      2   
samp_store_dur         12      6   
samp_vol_we_dna_ext    10      1   
tot_phosp              10      1   
samp_salinity          10      4   
tot_nitro              10      1   
conduc                  8      8   
samp_size               5      1   
num_replicons           4      2   
samp_collect_device     3      1   
sodium                  2      1   
elev                    1      1   
propagation             1      1   

                                                                   top freq  \
norm_env_package                                           waste water  399   
taxonomy_id                                                     527639  201   
env_medium                                                       water  119   
env_broad_scale                                       activated sludge   66   
id                                              BIOSAMPLE:SAMN02261241    1   
env_local_scale                                                 sludge   63   
taxonomy_name                                    wastewater metagenome  201   
env_package                               MIGS/MIMS/MIMARKS.wastewater  385   
package                                         MIMS.me.wastewater.5.0  363   
collection_date                                               Apr-2013   36   
geo_loc_name                                     Singapore: Ulu pandan   58   
investigation_type                                          metagenome  373   
lat_lon                                               1.3667 N 103.8 E   58   
project_name                                   Geographic Sewage Study   77   
ref_biomaterial      Acinetobacter, Aeromonas, and Trichococcus pop...   36   
ph                                                                 8.5    8   
samp_store_temp                                                    -20   24   
depth                                                          surface   22   
temp                                                                35    4   
samp_store_loc                                                 Freezer   24   
isol_growth_condt                                       not applicable   16   
phosphate                                                       2.5071    1   
turbidity                                                          9.1    1   
rel_to_oxygen                                                  aerobic    7   
samp_mat_process                    0.2 micrometer membrane filtration   10   
oxy_stat_samp                                                  aerobic    9   
samp_store_dur                                                 8 hours    2   
samp_vol_we_dna_ext                                              50 ml   10   
tot_phosp                                                     1.0 mg/l   10   
samp_salinity                                           10000 mg per L    4   
tot_nitro                                                      26 mg/l   10   
conduc                                                           0.215    1   
samp_siz

## Describe env_packages labled as 'sea water'

In [30]:
seaWaterDf = getReducedDatame(reducedDf[reducedDf.norm_env_package == 'sea water'].copy()) # note: a copy of the dataframe is being used
seaWaterDescribe = getDescibeDf(seaWaterDf)

In [31]:
seaWaterDf.shape

(13, 26)

In [32]:
seaWaterDescribe.sort_values(by='pct_non_null', ascending=False)

count unique  \
norm_env_package       13      1   
package                13      3   
env_local_scale        13      4   
taxonomy_id            13      4   
taxonomy_name          13      4   
id                     13     13   
geo_loc_name           13      4   
env_package            13      4   
isol_growth_condt      11      9   
collection_date        11      3   
trophic_level          11      3   
biotic_relationship    10      1   
project_name           10      2   
investigation_type     10      2   
ploidy                  9      2   
env_broad_scale         4      3   
depth                   4      3   
elev                    2      1   
host_taxid              2      1   
rel_to_oxygen           2      2   
env_medium              2      2   
lat_lon                 2      2   
num_replicons           1      1   
ref_biomaterial         1      1   
estimated_size          1      1   
temp                    1      1   

                                                                   top freq  \
norm_env_package                                             sea water   13   
package                                                    Generic.1.0   11   
env_local_scale                                        intertidal zone    9   
taxonomy_id                                                    1262161    9   
taxonomy_name                                      Pyropia haitanensis    9   
id                                              BIOSAMPLE:SAMN01818488    1   
geo_loc_name                                    China: Fujian Province    9   
env_package                                                   seawater    9   
isol_growth_condt                  21C, 50 mol photons m2 s1 (12L:13D)    2   
collection_date                                            19-Mar-2012    9   
trophic_level                                           photosynthetic    9   
biotic_relationship                                        free living   10   
project_name         Characterization of the global transcriptome f...    9   
investigation_type                                           eukaryote    9   
ploidy                                                         haploid    6   
env_broad_scale                                        estuarine biome    2   
depth                                                                0    2   
elev                                                                 0    2   
host_taxid                                                     1561972    2   
rel_to_oxygen                                              facultative    1   
env_medium                                      water, [ENVO:00002006]    1   
lat_lon                                               34.45 N 126.78 E    1   
num_replicons                                                        2    1   
ref_biomaterial                                         PMID: 19671726    1   
estimated_size                                                 2724951    1   
temp                                                        15 to 37 C    1   

                     pct_non_null  
norm_env_package           100.00  
package                    100.00  
env_local_scale            100.00  
taxonomy_id                100.00  
taxonomy_name              100.00  
id                         100.00  
geo_loc_name               100.00  
env_package                100.00  
isol_growth_condt           84.62  
collection_date             84.62  
trophic_level               84.62  
biotic_relationship         76.92  
project_name                76.92  
investigation_type          76.92  
ploidy                      69.23  
env_broad_scale             30.77  
depth                       30.77  
elev                        15.38  
host_taxid                  15.38  
rel_to_oxygen               15.38  
env_medium                  15.38  
lat_lon                     15.38  
num_replicons                7.69  
ref_biomaterial              7.69  
estimated_siz

## Describe env_packages labled as 'Deep-sea water'

In [34]:
deepSeaWaterDf = getReducedDatame(reducedDf[reducedDf.norm_env_package == 'Deep-sea water'].copy()) # note: a copy of the dataframe is being used
deepSeaWaterDescribe = getDescibeDf(deepSeaWaterDf)

In [35]:
deepSeaWaterDf.shape

(1, 21)

In [36]:
deepSeaWaterDescribe

count unique  \
num_replicons           1      1   
env_package             1      1   
geo_loc_name            1      1   
biotic_relationship     1      1   
project_name            1      1   
salinity                1      1   
investigation_type      1      1   
collection_date         1      1   
temp                    1      1   
env_broad_scale         1      1   
env_local_scale         1      1   
env_medium              1      1   
samp_collect_device     1      1   
lat_lon                 1      1   
depth                   1      1   
trophic_level           1      1   
id                      1      1   
taxonomy_id             1      1   
taxonomy_name           1      1   
package                 1      1   
norm_env_package        1      1   

                                                                  top freq  \
num_replicons                                                       1    1   
env_package                                            Deep-sea water    1   
geo_loc_name                                             Indian Ocean    1   
biotic_relationship                                       free living    1   
project_name         Complete genome sequence of Alcanivorax sp. IO_7    1   
salinity                                 0Ã¢ÂÂ15% (optimum at 3.5%)    1   
investigation_type                                   bacteria_archaea    1   
collection_date                                                  2017    1   
temp                  5Ã¢ÂÂ40Ã¢ÂÂ¯ÃÂ°C (optimum at 28Ã¢ÂÂ¯ÃÂ°C)    1   
env_broad_scale                                   Sea [ENVO:00000016]    1   
env_local_scale                 Sea water environment [ENVO:01000321]    1   
env_medium                                 Sea water [ENVO:00002149 ]    1   
samp_collect_device                         CTD-rosette water sampler    1   
lat_lon                                               27.75 S 63.80 E    1   
depth                                                     3980Ã¢ÂÂ¯m    1   
trophic_level                                             heterotroph    1   
id                                             BIOSAMPLE:SAMN14884473    1   
taxonomy_id                                                   2735303    1   
taxonomy_name                                    Alcanivorax sp. IO_7    1   
package                                                   MIGS.ba.5.0    1   
norm_env_package                                       Deep-sea water    1   

                     pct_non_null  
num_replicons               100.0  
env_package                 100.0  
geo_loc_name                100.0  
biotic_relationship         100.0  
project_name                100.0  
salinity                    100.0  
investigation_type          100.0  
collection_date             100.0  
temp                        100.0  
env_broad_scale             100.0  
env_local_scale             100.0  
env_medium                  100.0  
samp_collect_device         100.0  
lat_lon                     100.0  
depth                       100.0  
trophic_level               100.0  
id                          100.0  
taxonomy_id                 100.0  
taxonomy_name               100.0  
package                     100.0  
norm_env_package            100.0

## Describe env_packages labled as 'fresh water'

In [37]:
freshWaterDf = getReducedDatame(reducedDf[reducedDf.norm_env_package == 'fresh water'].copy()) # note: a copy of the dataframe is being used
freshWaterDescribe = getDescibeDf(freshWaterDf)

In [38]:
freshWaterDf.shape

(27, 13)

In [39]:
freshWaterDescribe

count unique                     top freq  pct_non_null
env_package         27      1             fresh water   27        100.00
host_taxid          27      4                    4530   10        100.00
geo_loc_name        27      2                     USA   17        100.00
elev                27      2                       0   17        100.00
env_broad_scale     27      2         estuarine biome   17        100.00
env_local_scale     27      2       large river biome   17        100.00
env_medium          10      1             fresh water   10         37.04
depth               27      1                       0   27        100.00
id                  27     27  BIOSAMPLE:SAMEA4036406    1        100.00
taxonomy_id         27      3                  449393   16        100.00
taxonomy_name       27      3   freshwater metagenome   16        100.00
package             27      1             Generic.1.0   27        100.00
norm_env_package    27      1             fresh water   27        100.00

## Describe env_packages labled as 'sterile water'

In [40]:
sterileWaterDf = getReducedDatame(reducedDf[reducedDf.norm_env_package == 'sterile water'].copy()) # note: a copy of the dataframe is being used
sterileWaterDescribe = getDescibeDf(sterileWaterDf)

In [41]:
sterileWaterDf.shape

(35, 14)

In [42]:
sterileWaterDescribe

count unique                     top freq  pct_non_null
env_package         35      1           sterile water   35         100.0
host_taxid          35      1                  256318   35         100.0
geo_loc_name        35      1              Costa Rica   35         100.0
elev                35      1                    1656   35         100.0
collection_date     35      1     2050-01-01 00:00:00   35         100.0
env_broad_scale     35      1             urban biome   35         100.0
env_local_scale     35      1       research facility   35         100.0
env_medium          35      1           sterile water   35         100.0
depth               35      1                       0   35         100.0
id                  35     35  BIOSAMPLE:SAMEA4083307    1         100.0
taxonomy_id         35      1                  256318   35         100.0
taxonomy_name       35      1              metagenome   35         100.0
package             35      1             Generic.1.0   35         100.0
norm_env_package    35      1           sterile water   35         100.0

## Describe env_packages labled as 'Coastal water body (ENVO:02000049)'

In [43]:
costalWaterDf = getReducedDatame(reducedDf[reducedDf.norm_env_package == 'Coastal water body (ENVO:02000049)'].copy()) # note: a copy of the dataframe is being used
costalWaterDescribe = getDescibeDf(costalWaterDf)

In [44]:
costalWaterDf.shape

(1, 19)

In [45]:
costalWaterDescribe

count unique  \
rel_to_oxygen           1      1   
env_package             1      1   
propagation             1      1   
samp_mat_process        1      1   
geo_loc_name            1      1   
biotic_relationship     1      1   
collection_date         1      1   
temp                    1      1   
env_broad_scale         1      1   
env_local_scale         1      1   
env_medium              1      1   
samp_collect_device     1      1   
lat_lon                 1      1   
trophic_level           1      1   
id                      1      1   
taxonomy_id             1      1   
taxonomy_name           1      1   
package                 1      1   
norm_env_package        1      1   

                                                                   top freq  \
rel_to_oxygen                                                   aerobe    1   
env_package                         Coastal water body (ENVO:02000049)    1   
propagation                                             binary fission    1   
samp_mat_process     Stored in the dark at 4ÃÂ°C until cyst germin...    1   
geo_loc_name                                       South Korea: Shiwha    1   
biotic_relationship                                        free living    1   
collection_date                                               Sep-2010    1   
temp                                                            21.3 C    1   
env_broad_scale                              Sea coast (ENVO:00000303)    1   
env_local_scale                              Sea floor (ENVO:00000482)    1   
env_medium                                                    seawater    1   
samp_collect_device                                         Ekman grab    1   
lat_lon                                               37.18 N 126.36 E    1   
trophic_level                                                mixotroph    1   
id                                              BIOSAMPLE:SAMN05904655    1   
taxonomy_id                                                    1872691    1   
taxonomy_name                                      Ansanella granifera    1   
package                                              MIGS.eu.water.5.0    1   
norm_env_package                    Coastal water body (ENVO:02000049)    1   

                     pct_non_null  
rel_to_oxygen               100.0  
env_package                 100.0  
propagation                 100.0  
samp_mat_process            100.0  
geo_loc_name                100.0  
biotic_relationship         100.0  
collection_date             100.0  
temp                        100.0  
env_broad_scale             100.0  
env_local_scale             100.0  
env_medium                  100.0  
samp_collect_device         100.0  
lat_lon                     100.0  
trophic_level               100.0  
id                          100.0  
taxonomy_id                 100.0  
taxonomy_name               100.0  
package                     100.0  
norm_env_package            100.0